import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/homepage/footer/Footer";
import ResponsiveNav from "@/components/homepage/navbar/responsiveNav";
import { CartProvider } from "@/app/context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <CartProvider>
          {/* ✅ DEPLOY DEBUG MARKER */}
          <div className="p-2 text-xs font-bold bg-yellow-200 text-black">
            LAYOUT DEBUG: if you don’t see this, Cloudflare isn’t deploying your latest code.
          </div>

          <ResponsiveNav />

          {/* GLOBAL OFFSET FOR FIXED NAV */}
          <main className="pt-40 md:pt-44">
            <div className="w-full container mx-auto mt-10">
              {children}
            </div>
          </main>

          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
